default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:206436832900:android:28a13ddc1e3a32784dd4d1", 
      firebase_cli_token:ENV["_FIREBASE_CLI_TOKEN"], 
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mahmoud.3ashry5555@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
    )
  end
end
